name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/BE-Nodejs:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/BE-Nodejs:latest

      - name: Deploy to VM
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          VM_IP: ${{ secrets.VM_IP }}
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
        run: |
          echo "${SSH_KEY}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -o StrictHostKeyChecking=no -o LogLevel=DEBUG -i /tmp/private_key ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/BE-Nodejs:latest
            sudo docker stop BE-Nodejs || true
            sudo docker rm BE-Nodejs || true
            sudo docker run -d --name BE-Nodejs -p 9000:9000 -v /var/log/BE-Nodejs:/var/log/BE-Nodejs --restart always ${{ secrets.DOCKER_HUB_USERNAME }}/BE-Nodejs:latest
          EOF
